### ISSUE TITLE
extraLongFactorials()

### ISSUE THREAD

**Issue by stas12go** [ibnomar94/Php-Extra-Long-Factorials#1]
Hello! There is no discription what should this undefined function do. Can you answer me please?

**Comment by ibnomar94** [comment]
Hello, this was a typing mistake, i forgot to change the name of the function. it is now fixed.

**Comment by ibnomar94** [comment]
> Hello! There is no discription what should this undefined function do. Can you answer me please?

please check now

**Comment by stas12go** [comment]
Good job mate!
